# Generated by Django 4.1.1 on 2022-10-08 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_programmer_about_alter_programmer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('level_of_mastery', models.CharField(blank=True, choices=[('Starter', 'Starter'), ('Basic', 'Basic'), ('Comfortable', 'Comfortable'), ('Skillfull', 'Skillfull'), ('Master', 'Master')], max_length=50, null=True)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.programmer')),
            ],
        ),
    ]
