# Generated by Django 4.1.1 on 2022-10-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='linkedIn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programmer',
            name='slug',
            field=models.SlugField(default='dkf1123222', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmer',
            name='speciality',
            field=models.CharField(default='Developer', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmer',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='gender',
            field=models.CharField(max_length=120),
        ),
    ]
