# Generated by Django 4.1.1 on 2022-10-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_programmer_linkedin_programmer_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
