# Generated by Django 4.1.1 on 2022-10-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_project_vote_techtools_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='dddddddsadfasd234', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
