# Generated by Django 4.1.1 on 2022-10-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_comment_commented_at_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='down_vote',
            field=models.ManyToManyField(blank=True, null=True, related_name='programmer_down', to='base.programmer'),
        ),
        migrations.AddField(
            model_name='project',
            name='up_vote',
            field=models.ManyToManyField(blank=True, null=True, related_name='programmer_up', to='base.programmer'),
        ),
    ]
